In [22]:
# Import all relevant libraries

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import skew
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

import warnings

warnings.filterwarnings("ignore")

In [25]:
guitar_data = pd.read_csv('../data/guitars02102022.csv')
guitars = guitar_data[['brand','model','condition','price']]

In [26]:
guitars.head()

     brand         model         condition    price
0  Warmoth  Stratocaster  Used – Very Good   950.00
1   Fender  Stratocaster         Brand New  1599.99
2  Eastman         T486B         Brand New  1319.00
3   Ibanez   Artist 2618  Used – Very Good  2499.00
4   Fender  Stratocaster  Used – Very Good  1299.99

In [27]:
data = pd.get_dummies(guitar_data[['brand','model','condition']])
data

,brand_Airline,brand_Alvarez,brand_B.C. Rich,brand_Charvel,brand_D'Angelico,brand_Danelectro,brand_Dean,brand_Duesenberg,brand_ESP,brand_EVH,...,model_X Series,model_generic/clone,model_special,condition_Brand New,condition_Used – B-Stock,condition_Used – Excellent,condition_Used – Good,condition_Used – Mint,condition_Used – Non Functioning,condition_Used – Very Good
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107102,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
107103,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
107104,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
107105,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
107106,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [38]:
#X_train, X_test, y_train, y_test = train_test_split(guitar_data.drop(['price'], axis=1), guitar_data['price'], test_size=0.2)

#Dividing data back into train & test
train =data[:len(y_train)]
test = data[len(y_train):]
#Printing thier shapes
print(train.shape, test.shape)

x_train, x_test, y_train, y_test = train_test_split(train, y_train, test_size=0.2, random_state=42)

(85685, 171) (21422, 171)

In [39]:
clf = RandomForestRegressor(n_estimators=100)

In [40]:
clf.fit(x_train, y_train)

RandomForestRegressor()

In [41]:
clf.score(x_test,y_test)

-0.0030301999294055637